"""create_normalized_tables

Revision ID: c37c61a3e9b1
Revises: 
Create Date: 2026-06-29 12:47:41.831002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37c61a3e9b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crime_heads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crime_heads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crime_heads_name'), ['name'], unique=True)

    op.create_table('districts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_districts_name'), ['name'], unique=True)

    op.create_table('crime_sub_heads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('crime_head_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['crime_head_id'], ['crime_heads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crime_sub_heads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crime_sub_heads_name'), ['name'], unique=False)

    op.create_table('police_stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district_id', sa.String(), nullable=False),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('base_latitude', sa.Float(), nullable=True),
    sa.Column('base_longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('police_stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_police_stations_name'), ['name'], unique=True)

    op.create_table('employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('badge_number', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['police_stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_badge_number'), ['badge_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_name'), ['name'], unique=False)

    op.create_table('case_masters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fir_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('crime_sub_head_id', sa.String(), nullable=True),
    sa.Column('offense_description', sa.String(), nullable=False),
    sa.Column('incident_summary', sa.String(), nullable=True),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crime_sub_head_id'], ['crime_sub_heads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['police_stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_masters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_masters_fir_number'), ['fir_number'], unique=True)

    op.create_table('accused',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case_masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accused', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accused_name'), ['name'], unique=False)

    op.create_table('chargesheet_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('sections', sa.String(), nullable=False),
    sa.Column('date_filed', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case_masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('complainant_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case_masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complainant_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complainant_details_name'), ['name'], unique=False)

    op.create_table('victims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case_masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('victims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_victims_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('victims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_victims_name'))

    op.drop_table('victims')
    with op.batch_alter_table('complainant_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complainant_details_name'))

    op.drop_table('complainant_details')
    op.drop_table('chargesheet_details')
    with op.batch_alter_table('accused', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accused_name'))

    op.drop_table('accused')
    with op.batch_alter_table('case_masters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_masters_fir_number'))

    op.drop_table('case_masters')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_name'))
        batch_op.drop_index(batch_op.f('ix_employees_badge_number'))

    op.drop_table('employees')
    with op.batch_alter_table('police_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_police_stations_name'))

    op.drop_table('police_stations')
    with op.batch_alter_table('crime_sub_heads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crime_sub_heads_name'))

    op.drop_table('crime_sub_heads')
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_districts_name'))

    op.drop_table('districts')
    with op.batch_alter_table('crime_heads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crime_heads_name'))

    op.drop_table('crime_heads')
    # ### end Alembic commands ###
